version: '3.7'

services:

  risksrv:
    image: intersystemsdc/irisdemo-demo-readmission:risksrv-version-2.4.0
    hostname: risksrv
    init: true
    ports:
    - "9093:1972" # 51773 is the superserver default port
    - "9092:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ./hl7files/
      target: /hl7files

  riskengine:   # Readmission Risk LACE Service
    image: intersystemsdc/irisdemo-demo-readmission:riskengine-version-2.4.0
    hostname: riskengine
    depends_on:
    - risksrv
    init: true
    ports:
    - "9095:1972" # 51773 or 1972 is the superserver default port
    - "9094:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ./common_shared/
      target: /common_shared

  hisdb:
    image: intersystemsdc/irisdemo-demo-readmission:hisdb-version-2.4.0
    hostname: hisdb
    depends_on:
    - riskengine
    init: true
    ports:
    - "9097:1972" # 51773 is the superserver default port
    - "9096:52773" # 52773 is the webserver/management portal port

  hisui:
    image: intersystemsdc/irisdemo-demo-readmission:hisui-version-2.4.0
    hostname: hisui
    depends_on:
    - hisdb
    init: true
    ports:
    - "9098:4200" # Where Nodejs Will be listening

  zeppelin:
    image: intersystemsdc/irisdemo-base-zeppelin:latest
    init: true
    depends_on:
    - hisui
    ports:
    - "10000:8080"     # Zeppelin
    - "10001:4040"     # Zeppelin Spark UI
    volumes:
    # - common_shared:/common_shared   # The production will be looking into this folder for new PMML files
                                       # that will be sent by the zeppelin service.
    - type: bind
      source: ./common_shared/
      target: /common_shared
    - type: bind
      source: ./zeppelin/shared/zeppelin/logs
      target: /shared/zeppelin/logs
    - type: bind
      source: ./zeppelin/shared/zeppelin/conf
      target: /shared/zeppelin/conf
    - type: bind
      source: ./zeppelin/shared/zeppelin/notebook
      target: /shared/zeppelin/notebook
    - type: bind
      source: ./zeppelin/shared/zeppelin/interpreter/jdbc/interpreter-setting.json
      target: /zeppelin/interpreter/jdbc/interpreter-setting.json
    - type: bind
      source: ./zeppelin/shared/zeppelin/interpreter/python/interpreter-setting.json
      target: /zeppelin/interpreter/python/interpreter-setting.json
    - type: bind
      source: ./zeppelin/shared/zeppelin/interpreter/r/interpreter-setting.json
      target: /zeppelin/interpreter/r/interpreter-setting.json
    - type: bind
      source: ./zeppelin/shared/zeppelin/interpreter/spark/interpreter-setting.json
      target: /zeppelin/interpreter/spark/interpreter-setting.json
    - type: bind
      source: ./zeppelin/shared/zeppelin/interpreter/sparql/interpreter-setting.json
      target: /zeppelin/interpreter/sparql/interpreter-setting.json

    environment:
    - IRIS_MASTER_HOST=riskengine # DNS based on the name of the service!
    - IRIS_MASTER_PORT=1972
    - IRIS_MASTER_USERNAME=SuperUser
    - IRIS_MASTER_PASSWORD=sys
    - IRIS_MASTER_NAMESPACE=APPINT

  sparkmaster:
    image: intersystemsdc/irisdemo-base-spark-iris:latest
    hostname: sparkmaster # Must be always sparkmaster
    init: true
    depends_on:
    - zeppelin
    environment:
      SPARK_NODE_TYPE: Master
      SPARK_PUBLIC_DNS: localhost
      IRIS_MASTER_HOST: riskengine
      IRIS_MASTER_PORT: 1972
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080   # Spark Master Portal
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
    - type: bind
      source: ./common_shared/
      target: /common_shared

  worker1:
    depends_on:
      - sparkmaster
    image: intersystemsdc/irisdemo-base-spark-iris:latest
    hostname: worker1
    init: true
    environment:
      IRIS_MASTER_HOST: riskengine
      IRIS_MASTER_PORT: 1972
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 8g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081   # Spark Worker Portal
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
    - type: bind
      source: ./common_shared/
      target: /common_shared

  # worker2:
  #   depends_on:
  #     - sparkmaster
  #   image: intersystemsdc/irisdemo-base-spark-iris:latest
  #   hostname: worker2
  #   init: true
  #   environment:
  #     IRIS_MASTER_HOST: riskengine
  #     IRIS_MASTER_PORT: 1972
  #     IRIS_MASTER_USERNAME: SuperUser
  #     IRIS_MASTER_PASSWORD: sys
  #     IRIS_MASTER_NAMESPACE: APPINT

  #     SPARK_NODE_TYPE: Worker
  #     SPARK_WORKER_CORES: 1
  #     SPARK_WORKER_MEMORY: 8g   # You can give more memory to your work if you are getting errors when using Spark
  #     SPARK_WORKER_PORT: 8882
  #     SPARK_WORKER_WEBUI_PORT: 8082
  #     SPARK_PUBLIC_DNS: localhost
  #   ports:
  #     - 8082:8082   # Spark Worker Portal
  #   volumes:
  #   # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
  #   - type: bind
  #     source: ./common_shared/
  #     target: /common_shared
